/**
 * The bundled food library: what a person actually logs, curated by hand.
 *
 * Auto-selecting from USDA SR Legacy by category gives you ucuhuba butter and
 * boiled breadfruit seeds — technically food, useless in a tracker. So each row
 * here names the food the way he would search for it, and lists the terms that
 * find it in the USDA data. scripts/build-usda-foods.mjs resolves the terms to
 * the shortest matching USDA description and reports anything it cannot find.
 *
 *   [display name, [required terms, all must appear], category hint?]
 *
 * Terms are matched case-insensitively against the USDA description. Add a term
 * to disambiguate, not to be precise: shortest-match already prefers the plain
 * entry over "trimmed to 1/8\" fat, all grades, cooked, braised".
 */

const M = "Beef Products", P = "Poultry Products", PK = "Pork Products";
const FISH = "Finfish and Shellfish Products", D = "Dairy and Egg Products";
const V = "Vegetables and Vegetable Products", F = "Fruits and Fruit Juices";
const G = "Cereal Grains and Pasta", L = "Legumes and Legume Products";
const N = "Nut and Seed Products", FAT = "Fats and Oils", BK = "Baked Products";
const CER = "Breakfast Cereals", SW = "Sweets", SN = "Snacks";
const SLM = "Sausages and Luncheon Meats", BEV = "Beverages";
const SAU = "Soups, Sauces, and Gravies", SP = "Spices and Herbs";
const LAMB = "Lamb, Veal, and Game Products";

export const FOODS = [
  /* ---------------------------------------------------------- poultry */
  ["Chicken breast, raw", ["chicken", "breast", "meat only", "raw"], P],
  ["Chicken breast, roasted", ["chicken", "breast", "meat only", "roasted"], P],
  ["Chicken breast, grilled", ["chicken", "breast", "grilled"], P],
  ["Chicken breast with skin, roasted", ["chicken", "breast", "meat and skin", "roasted"], P],
  ["Chicken thigh, raw", ["chicken", "thigh", "meat only", "raw"], P],
  ["Chicken thigh, roasted", ["chicken", "thigh", "meat only", "roasted"], P],
  ["Chicken drumstick, roasted", ["chicken", "drumstick", "meat only", "roasted"], P],
  ["Chicken wing, roasted", ["chicken", "wing", "meat only", "roasted"], P],
  ["Chicken, ground, raw", ["chicken", "ground", "raw"], P],
  ["Chicken, ground, cooked", ["chicken", "ground", "cooked"], P],
  ["Chicken liver, cooked", ["chicken", "liver", "cooked"], P],
  ["Chicken, rotisserie, breast", ["chicken", "rotisserie", "breast"], P],
  ["Turkey breast, roasted", ["turkey", "breast", "meat only", "roasted"], P],
  ["Turkey, ground, raw", ["turkey", "ground", "raw"], P],
  ["Turkey, ground, cooked", ["turkey", "ground", "cooked"], P],
  ["Turkey, dark meat, roasted", ["turkey", "dark meat", "roasted"], P],
  ["Duck breast, roasted", ["duck", "domesticated", "meat only", "roasted"], P],
  ["Egg, whole, raw", ["egg", "whole", "raw", "fresh"], D],
  ["Egg, whole, hard-boiled", ["egg", "whole", "hard-boiled"], D],
  ["Egg, whole, fried", ["egg", "whole", "fried"], D],
  ["Egg, whole, scrambled", ["egg", "whole", "scrambled"], D],
  ["Egg white, raw", ["egg", "white", "raw", "fresh"], D],
  ["Egg yolk, raw", ["egg", "yolk", "raw", "fresh"], D],
  ["Egg substitute, liquid", ["egg substitute", "liquid"], D],

  /* ------------------------------------------------------------- beef */
  ["Ground beef, 93% lean, raw", ["beef, ground", "93% lean", "raw"], M],
  ["Ground beef, 93% lean, cooked", ["beef, ground", "93% lean", "pan-broiled"], M],
  ["Ground beef, 90% lean, raw", ["beef, ground", "90% lean", "raw"], M],
  ["Ground beef, 85% lean, raw", ["beef, ground", "85% lean", "raw"], M],
  ["Ground beef, 85% lean, cooked", ["beef, ground", "85% lean", "pan-broiled"], M],
  ["Ground beef, 80% lean, raw", ["beef, ground", "80% lean", "raw"], M],
  ["Ground beef, 80% lean, cooked", ["beef, ground", "80% lean", "pan-broiled"], M],
  ["Ground beef, 95% lean, raw", ["beef, ground", "95% lean", "raw"], M],
  ["Beef sirloin steak, broiled", ["beef", "top sirloin", "lean only", "broiled"], M],
  ["Beef ribeye steak, broiled", ["beef", "rib eye", "broiled"], M],
  ["Beef tenderloin, broiled", ["beef", "tenderloin", "lean only", "broiled"], M],
  ["Beef flank steak, broiled", ["beef", "flank", "broiled"], M],
  ["Beef skirt steak, broiled", ["beef", "skirt steak", "broiled"], M],
  ["Beef chuck roast, braised", ["beef", "chuck", "pot roast", "lean only", "braised"], M],
  ["Beef brisket, braised", ["beef", "brisket", "lean only", "braised", "!new zealand"], M],
  ["Beef round, roasted", ["beef", "eye of round", "lean only", "roasted"], M],
  ["Beef liver, cooked", ["beef", "liver", "braised"], M],
  ["Beef jerky", ["beef jerky"], SN],
  ["Corned beef, cooked", ["corned beef", "brisket", "cooked"], M],
  ["Veal cutlet, cooked", ["veal", "cutlet", "cooked"], LAMB],
  ["Lamb chop, broiled", ["lamb", "loin", "lean only", "broiled"], LAMB],
  ["Lamb, ground, broiled", ["lamb", "ground", "broiled"], LAMB],
  ["Lamb leg, roasted", ["lamb", "leg", "lean only", "roasted"], LAMB],
  ["Bison, ground, cooked", ["bison", "ground", "cooked"], LAMB],
  ["Venison, roasted", ["deer", "roasted"], LAMB],

  /* ------------------------------------------------------------- pork */
  ["Pork chop, broiled", ["pork", "loin", "chops", "lean only", "broiled"], PK],
  ["Pork tenderloin, roasted", ["pork", "tenderloin", "lean only", "roasted"], PK],
  ["Pork loin, roasted", ["pork", "loin", "lean only", "roasted"], PK],
  ["Pork shoulder, roasted", ["pork, fresh", "shoulder", "lean only", "roasted"], PK],
  ["Pork, ground, cooked", ["pork", "ground", "cooked"], PK],
  ["Bacon, cooked", ["bacon", "cooked"], PK],
  ["Canadian bacon, cooked", ["canadian bacon"], PK],
  ["Ham, sliced, lean", ["pork, cured, ham", "extra lean", "roasted", "!regular"], PK],
  ["Pork ribs, cooked", ["pork", "spareribs", "cooked"], PK],
  ["Ham, roasted", ["pork, cured, ham", "boneless", "regular", "roasted"], PK],
  ["Salami", ["salami", "pork", "beef"], SLM],
  ["Pepperoni", ["pepperoni"], SLM],
  ["Bratwurst", ["bratwurst"], SLM],
  ["Italian sausage, cooked", ["sausage, italian", "pork", "cooked"], SLM],
  ["Hot dog, beef", ["frankfurter", "beef"], SLM],
  ["Chicken sausage", ["sausage", "chicken", "!polish", "!turkey"], SLM],
  ["Turkey deli slices", ["turkey breast", "sliced"], SLM],
  ["Bologna", ["bologna", "beef"], SLM],
  ["Chorizo", ["chorizo"], SLM],

  /* ------------------------------------------------------- fish & sea */
  ["Salmon, Atlantic, farmed, raw", ["salmon", "atlantic", "farmed", "raw"], FISH],
  ["Salmon, Atlantic, farmed, cooked", ["salmon", "atlantic", "farmed", "cooked"], FISH],
  ["Salmon, sockeye, cooked", ["salmon", "sockeye", "cooked"], FISH],
  ["Salmon, canned", ["salmon", "pink", "canned"], FISH],
  ["Smoked salmon", ["salmon", "smoked"], FISH],
  ["Tuna, canned in water", ["tuna", "light", "canned in water"], FISH],
  ["Tuna, canned in oil", ["tuna", "canned in oil"], FISH],
  ["Tuna steak, cooked", ["tuna", "yellowfin", "cooked"], FISH],
  ["Cod, cooked", ["cod", "atlantic", "cooked"], FISH],
  ["Tilapia, cooked", ["tilapia", "cooked"], FISH],
  ["Halibut, cooked", ["halibut", "cooked", "!greenland"], FISH],
  ["Mahi mahi, cooked", ["mahimahi", "cooked"], FISH],
  ["Sardines, canned", ["sardine", "canned"], FISH],
  ["Mackerel, cooked", ["mackerel", "atlantic", "cooked"], FISH],
  ["Trout, cooked", ["trout", "rainbow", "cooked"], FISH],
  ["Shrimp, raw", ["shrimp", "raw"], FISH],
  ["Shrimp, cooked", ["shrimp", "cooked"], FISH],
  ["Crab, cooked", ["crab", "blue", "cooked"], FISH],
  ["Lobster, cooked", ["lobster", "cooked"], FISH],
  ["Scallops, cooked", ["scallop", "cooked"], FISH],
  ["Mussels, cooked", ["mussel", "cooked"], FISH],
  ["Oysters, raw", ["oyster", "raw"], FISH],
  ["Squid, cooked", ["squid", "cooked"], FISH],
  ["Anchovies, canned", ["anchovy", "canned"], FISH],

  /* ------------------------------------------------------------ dairy */
  ["Milk, whole", ["milk", "whole", "3.25%"], D],
  ["Milk, 2%", ["milk", "reduced fat", "2%"], D],
  ["Milk, 1%", ["milk, lowfat", "1% milkfat"], D],
  ["Milk, skim", ["milk", "nonfat", "fat free"], D],
  ["Chocolate milk", ["milk, chocolate", "fluid", "!shake"], D],
  ["Buttermilk", ["buttermilk", "lowfat"], D],
  ["Heavy cream", ["cream", "heavy whipping"], D],
  ["Half and half", ["cream", "half and half"], D],
  ["Sour cream", ["cream, sour", "cultured", "!reduced"], D],
  ["Greek yogurt, plain, nonfat", ["yogurt", "greek", "plain", "nonfat"], D],
  ["Greek yogurt, plain, whole milk", ["yogurt", "greek", "plain", "whole milk"], D],
  ["Greek yogurt, plain, 2%", ["yogurt", "greek", "plain", "lowfat"], D],
  ["Yogurt, plain, whole milk", ["yogurt", "plain", "whole milk"], D],
  ["Yogurt, plain, low fat", ["yogurt", "plain", "low fat"], D],
  ["Yogurt, fruit, low fat", ["yogurt", "fruit", "low fat"], D],
  ["Cottage cheese, 2%", ["cheese, cottage", "2% milkfat"], D],
  ["Cottage cheese, 1%", ["cheese, cottage", "1% milkfat"], D],
  ["Cottage cheese, nonfat", ["cheese, cottage", "nonfat"], D],
  ["Ricotta cheese, part skim", ["ricotta", "part skim"], D],
  ["Cheddar cheese", ["cheese", "cheddar"], D],
  ["Mozzarella, part skim", ["cheese", "mozzarella", "part skim"], D],
  ["Mozzarella, whole milk", ["cheese", "mozzarella", "whole milk"], D],
  ["Parmesan, grated", ["cheese", "parmesan", "grated"], D],
  ["Swiss cheese", ["cheese", "swiss"], D],
  ["Feta cheese", ["cheese", "feta"], D],
  ["Goat cheese", ["cheese", "goat", "soft"], D],
  ["Cream cheese", ["cheese, cream"], D],
  ["Blue cheese", ["cheese", "blue"], D],
  ["Provolone", ["cheese", "provolone"], D],
  ["American cheese", ["cheese, pasteurized process, american", "!spread", "!low fat"], D],
  ["Brie", ["cheese", "brie"], D],
  ["String cheese", ["cheese, mozzarella", "low moisture, part-skim"], D],
  ["Butter, salted", ["butter", "salted"], FAT],
  ["Butter, unsalted", ["butter", "without salt", "!light", "!whipped"], FAT],
  ["Ghee", ["butter oil", "anhydrous"], FAT],
  ["Whipped cream", ["cream", "whipped", "pressurized"], D],
  ["Ice cream, vanilla", ["ice cream", "vanilla"], SW],
  ["Ice cream, chocolate", ["ice cream", "chocolate"], SW],
  ["Kefir, plain", ["kefir"], D],
  ["Almond milk, unsweetened", ["almond milk", "unsweetened"], BEV],
  ["Soy milk, unsweetened", ["soymilk", "unsweetened"], BEV],
  ["Coconut milk beverage", ["beverages, coconut milk", "sweetened"], BEV],
  ["Coconut milk, canned", ["coconut milk", "canned"], V],

  /* ------------------------------------------------------ grains & bread */
  ["White rice, cooked", ["rice", "white", "long-grain", "cooked"], G],
  ["Brown rice, cooked", ["rice", "brown", "long-grain", "cooked"], G],
  ["Basmati rice, cooked", ["rice", "long-grain", "parboiled", "cooked"], G],
  ["Wild rice, cooked", ["wild rice", "cooked"], G],
  ["Quinoa, cooked", ["quinoa", "cooked"], G],
  ["Quinoa, uncooked", ["quinoa", "uncooked"], G],
  ["Oats, rolled, dry", ["cereals, oats", "not fortified", "dry"], CER],
  ["Oatmeal, cooked", ["cereals", "oats", "cooked", "water"], CER],
  ["Oats, instant, dry", ["cereals, oats", "instant", "plain, dry"], CER],
  ["Pasta, cooked", ["pasta, cooked, enriched"], G],
  ["Pasta, whole wheat, cooked", ["pasta, whole-wheat", "cooked"], G],
  ["Pasta, dry", ["pasta", "dry", "enriched"], G],
  ["Couscous, cooked", ["couscous", "cooked"], G],
  ["Barley, cooked", ["barley", "pearled", "cooked"], G],
  ["Buckwheat groats, cooked", ["buckwheat groats", "cooked"], G],
  ["Bulgur, cooked", ["bulgur", "cooked"], G],
  ["Farro", ["spelt", "cooked"], G],
  ["Millet, cooked", ["millet", "cooked"], G],
  ["Cornmeal, dry", ["cornmeal", "degermed", "enriched"], G],
  ["Grits, cooked", ["corn grits", "cooked", "water"], CER],
  ["Flour, all-purpose", ["wheat flour", "all-purpose", "enriched", "!unenriched", "!self-rising"], G],
  ["Flour, whole wheat", ["wheat flour", "whole-grain"], G],
  ["Wheat germ", ["wheat germ", "crude"], G],
  ["Bread, white", ["bread", "white", "commercially prepared", "!toasted"], BK],
  ["Bread, whole wheat", ["bread", "whole-wheat", "commercially prepared"], BK],
  ["Bread, multigrain", ["bread", "multi-grain"], BK],
  ["Bread, rye", ["bread", "rye"], BK],
  ["Bread, sourdough", ["bread", "french or vienna", "!whole wheat"], BK],
  ["Bagel, plain", ["bagels", "plain"], BK],
  ["English muffin", ["muffins", "english", "plain"], BK],
  ["Tortilla, flour", ["tortillas", "flour", "shelf stable"], BK],
  ["Tortilla, corn", ["tortillas", "corn"], BK],
  ["Pita bread", ["bread", "pita", "white"], BK],
  ["Naan", ["naan"], BK],
  ["Hamburger bun", ["rolls", "hamburger", "plain"], BK],
  ["Hot dog bun", ["rolls", "hot dog", "!whole wheat"], BK],
  ["Croissant, butter", ["croissants", "butter"], BK],
  ["Biscuit", ["biscuits", "plain", "refrigerated dough", "baked"], BK],
  ["Pancakes", ["pancakes", "plain", "prepared from recipe"], BK],
  ["Waffles, frozen", ["waffles", "plain", "frozen"], BK],
  ["French toast", ["french toast", "prepared from recipe"], BK],
  ["Crackers, saltine", ["crackers", "saltines", "!fat-free", "!unsalted"], BK],
  ["Crackers, whole wheat", ["crackers", "whole-wheat"], BK],
  ["Rice cake", ["rice cakes", "brown rice", "plain"], BK],
  ["Breadcrumbs, dry", ["bread, crumbs", "dry, grated, plain"], BK],
  ["Cereal, corn flakes", ["cereals ready-to-eat", "corn flakes"], CER],
  ["Cereal, bran flakes", ["cereals ready-to-eat", "bran flakes"], CER],
  ["Cereal, granola", ["granola", "homemade"], CER],
  ["Cereal, Cheerios", ["cereals ready-to-eat", "cheerios"], CER],
  ["Cereal, shredded wheat", ["shredded wheat", "original spoon-size"], CER],
  ["Cereal, puffed rice", ["cereals ready-to-eat", "rice", "puffed"], CER],

  /* ------------------------------------------------------------ legumes */
  ["Black beans, cooked", ["beans", "black", "cooked", "without salt"], L],
  ["Black beans, canned", ["beans", "black", "canned"], L],
  ["Kidney beans, cooked", ["beans", "kidney", "cooked", "without salt"], L],
  ["Pinto beans, cooked", ["beans", "pinto", "cooked", "without salt"], L],
  ["Navy beans, cooked", ["beans", "navy", "cooked", "without salt"], L],
  ["White beans, cooked", ["beans", "white", "cooked", "without salt"], L],
  ["Chickpeas, cooked", ["chickpeas", "cooked", "without salt"], L],
  ["Chickpeas, canned", ["chickpeas", "canned"], L],
  ["Lentils, cooked", ["lentils", "cooked", "without salt"], L],
  ["Split peas, cooked", ["peas", "split", "cooked", "without salt"], L],
  ["Edamame, cooked", ["soybeans, green", "cooked", "without salt"], V],
  ["Refried beans, canned", ["refried beans", "canned"], L],
  ["Baked beans, canned", ["beans", "baked", "canned", "plain"], L],
  ["Hummus", ["hummus", "commercial"], L],
  ["Tofu, firm", ["tofu", "raw", "firm"], L],
  ["Tofu, silken", ["tofu", "silken"], L],
  ["Tempeh", ["tempeh"], L],
  ["Soybeans, cooked", ["soybeans", "mature", "cooked"], L],
  ["Peanut butter, smooth", ["peanut butter", "smooth", "!reduced"], L],
  ["Peanut butter, chunky", ["peanut butter", "chunk"], L],
  ["Peanuts, roasted", ["peanuts", "dry-roasted"], L],
  ["Soy protein isolate", ["soy protein isolate"], L],

  /* --------------------------------------------------------- nuts, oils */
  ["Almonds", ["nuts", "almonds", "dry roasted"], N],
  ["Almonds, raw", ["nuts, almonds"], N],
  ["Almond butter", ["almond butter", "plain"], N],
  ["Walnuts", ["nuts", "walnuts", "english"], N],
  ["Pecans", ["nuts", "pecans"], N],
  ["Cashews", ["nuts", "cashew nuts", "dry roasted"], N],
  ["Cashew butter", ["cashew butter", "plain"], N],
  ["Pistachios", ["nuts", "pistachio", "dry roasted"], N],
  ["Macadamia nuts", ["nuts", "macadamia"], N],
  ["Hazelnuts", ["nuts", "hazelnuts"], N],
  ["Brazil nuts", ["nuts", "brazilnuts"], N],
  ["Pine nuts", ["nuts", "pine nuts"], N],
  ["Sunflower seeds", ["seeds", "sunflower seed kernels", "dry roasted"], N],
  ["Pumpkin seeds", ["seeds", "pumpkin", "roasted"], N],
  ["Chia seeds", ["seeds", "chia seeds", "dried"], N],
  ["Flax seeds", ["seeds", "flaxseed"], N],
  ["Sesame seeds", ["seeds", "sesame seeds", "whole"], N],
  ["Hemp seeds", ["seeds", "hemp seed"], N],
  ["Tahini", ["tahini"], N],
  ["Coconut, shredded, unsweetened", ["coconut meat", "dried", "!creamed", "!sweetened"], N],
  ["Olive oil", ["oil", "olive", "salad or cooking"], FAT],
  ["Canola oil", ["oil", "canola"], FAT],
  ["Avocado oil", ["oil", "avocado"], FAT],
  ["Coconut oil", ["oil", "coconut"], FAT],
  ["Vegetable oil", ["oil", "soybean", "salad or cooking"], FAT],
  ["Sesame oil", ["oil", "sesame"], FAT],
  ["Mayonnaise", ["mayonnaise", "soybean oil"], FAT],
  ["Mayonnaise, light", ["mayonnaise", "light"], FAT],
  ["Ranch dressing", ["salad dressing", "ranch"], FAT],
  ["Italian dressing", ["salad dressing", "italian", "!fat-free", "!reduced"], FAT],
  ["Caesar dressing", ["salad dressing", "caesar", "!fat-free", "!low calorie"], FAT],
  ["French dressing", ["salad dressing", "french dressing", "!fat-free", "!reduced"], FAT],
  ["Cooking spray", ["oil", "PAM", "spray"], FAT],

  /* --------------------------------------------------------- vegetables */
  ["Broccoli, raw", ["broccoli", "raw"], V],
  ["Broccoli, cooked", ["broccoli", "cooked", "boiled"], V],
  ["Cauliflower, raw", ["cauliflower", "raw"], V],
  ["Cauliflower, cooked", ["cauliflower", "cooked", "boiled"], V],
  ["Spinach, raw", ["spinach", "raw"], V],
  ["Spinach, cooked", ["spinach", "cooked", "boiled"], V],
  ["Kale, raw", ["kale", "raw"], V],
  ["Romaine lettuce", ["lettuce", "cos or romaine", "raw"], V],
  ["Iceberg lettuce", ["lettuce", "iceberg", "raw"], V],
  ["Arugula", ["arugula", "raw"], V],
  ["Cabbage, raw", ["cabbage", "raw"], V],
  ["Brussels sprouts, cooked", ["brussels sprouts", "cooked"], V],
  ["Asparagus, cooked", ["asparagus", "cooked", "boiled"], V],
  ["Green beans, cooked", ["beans", "snap", "green", "cooked"], V],
  ["Carrots, raw", ["carrots", "raw"], V],
  ["Carrots, cooked", ["carrots", "cooked", "boiled"], V],
  ["Bell pepper, red, raw", ["peppers", "sweet", "red", "raw"], V],
  ["Bell pepper, green, raw", ["peppers", "sweet", "green", "raw"], V],
  ["Jalapeno pepper, raw", ["peppers", "jalapeno", "raw"], V],
  ["Cucumber, raw", ["cucumber", "peeled", "raw"], V],
  ["Celery, raw", ["celery", "raw"], V],
  ["Tomato, raw", ["tomatoes", "red", "ripe", "raw"], V],
  ["Sun-dried tomatoes", ["tomatoes, sun-dried"], V],
  ["Tomatoes, canned, diced", ["tomatoes", "canned", "packed in tomato juice"], V],
  ["Tomato paste", ["tomato products", "canned", "paste"], V],
  ["Tomato sauce", ["tomato products", "canned", "sauce"], V],
  ["Salsa", ["salsa", "ready-to-serve"], SAU],
  ["Onion, raw", ["onions", "raw"], V],
  ["Onion, cooked", ["onions", "cooked", "boiled"], V],
  ["Green onion", ["onions", "spring", "raw"], V],
  ["Garlic, raw", ["garlic", "raw"], V],
  ["Mushrooms, raw", ["mushrooms", "white", "raw"], V],
  ["Mushrooms, cooked", ["mushrooms", "white", "cooked"], V],
  ["Zucchini, raw", ["squash", "zucchini", "raw", "!baby"], V],
  ["Zucchini, cooked", ["squash", "zucchini", "cooked"], V],
  ["Butternut squash, cooked", ["squash", "butternut", "cooked"], V],
  ["Eggplant, cooked", ["eggplant", "cooked"], V],
  ["Beets, cooked", ["beets", "cooked", "boiled"], V],
  ["Corn, cooked", ["corn", "sweet", "yellow", "cooked"], V],
  ["Corn, canned", ["corn", "sweet", "yellow", "canned", "whole kernel"], V],
  ["Peas, green, cooked", ["peas", "green", "cooked", "boiled"], V],
  ["Potato, baked", ["potatoes", "russet", "baked", "flesh and skin"], V],
  ["Potato, boiled", ["potatoes", "boiled", "cooked in skin", "flesh"], V],
  ["Potato, mashed", ["potatoes, mashed", "home-prepared", "whole milk"], V],
  ["French fries", ["potatoes", "french fried", "oven-heated"], V],
  ["Sweet potato, baked", ["sweet potato", "cooked", "baked in skin"], V],
  ["Sweet potato, boiled", ["sweet potato", "cooked", "boiled"], V],
  ["Avocado", ["avocados", "raw", "california"], F],
  ["Olives, black", ["olives", "ripe", "canned"], V],
  ["Olives, green", ["olives", "pickled", "green"], V],
  ["Pickles, dill", ["pickles", "cucumber", "dill"], V],
  ["Sauerkraut", ["sauerkraut", "canned"], V],
  ["Kimchi", ["cabbage", "kimchi"], V],
  ["Seaweed, nori", ["seaweed", "laver", "raw"], V],
  ["Bean sprouts", ["mung beans", "sprouted", "raw"], V],
  ["Artichoke, cooked", ["artichokes", "cooked", "boiled"], V],
  ["Okra, cooked", ["okra", "cooked", "boiled"], V],
  ["Radish, raw", ["radishes", "raw"], V],
  ["Turnip, cooked", ["turnips", "cooked", "boiled"], V],
  ["Pumpkin, canned", ["pumpkin", "canned", "without salt"], V],
  ["Cabbage, cooked", ["cabbage", "cooked, boiled"], V],

  /* -------------------------------------------------------------- fruit */
  ["Apple, raw", ["apples", "raw", "with skin"], F],
  ["Applesauce, unsweetened", ["applesauce", "canned", "unsweetened"], F],
  ["Banana, raw", ["bananas", "raw"], F],
  ["Orange, raw", ["oranges", "raw", "all commercial varieties"], F],
  ["Clementine", ["tangerines", "raw"], F],
  ["Grapefruit, raw", ["grapefruit", "raw", "pink and red"], F],
  ["Lemon, raw", ["lemons", "raw", "without peel"], F],
  ["Lime, raw", ["limes", "raw"], F],
  ["Strawberries, raw", ["strawberries", "raw"], F],
  ["Blueberries, raw", ["blueberries", "raw"], F],
  ["Raspberries, raw", ["raspberries", "raw"], F],
  ["Blackberries, raw", ["blackberries", "raw"], F],
  ["Grapes, raw", ["grapes", "red or green", "raw"], F],
  ["Watermelon, raw", ["watermelon", "raw"], F],
  ["Cantaloupe, raw", ["melons", "cantaloupe", "raw"], F],
  ["Honeydew, raw", ["melons", "honeydew", "raw"], F],
  ["Pineapple, raw", ["pineapple", "raw"], F],
  ["Mango, raw", ["mangos", "raw"], F],
  ["Papaya, raw", ["papayas", "raw"], F],
  ["Peach, raw", ["peaches", "raw"], F],
  ["Pear, raw", ["pears", "raw"], F],
  ["Plum, raw", ["plums", "raw"], F],
  ["Cherries, raw", ["cherries", "sweet", "raw"], F],
  ["Kiwi, raw", ["kiwifruit", "green", "raw"], F],
  ["Pomegranate, raw", ["pomegranates", "raw"], F],
  ["Cranberries, dried", ["cranberries", "dried", "sweetened"], F],
  ["Raisins", ["raisins", "seedless", "!golden"], F],
  ["Dates, medjool", ["dates", "medjool"], F],
  ["Prunes", ["plums", "dried", "uncooked"], F],
  ["Dried apricots", ["apricots", "dried", "uncooked"], F],
  ["Dried figs", ["figs", "dried", "uncooked"], F],
  ["Banana chips", ["snacks", "banana chips"], SN],
  ["Fruit cocktail, canned", ["fruit cocktail", "canned", "juice"], F],
  ["Peaches, canned", ["peaches", "canned", "juice pack"], F],
  ["Pineapple, canned", ["pineapple", "canned", "juice pack"], F],
  ["Blueberries, frozen", ["blueberries", "frozen", "unsweetened"], F],

  /* ---------------------------------------------------------- beverages */
  ["Orange juice", ["orange juice", "raw"], F],
  ["Apple juice", ["apple juice", "canned or bottled", "unsweetened"], F],
  ["Cranberry juice cocktail", ["cranberry juice cocktail", "bottled"], BEV],
  ["Grape juice", ["grape juice", "canned or bottled", "unsweetened"], F],
  ["Lemonade", ["lemonade", "powder", "prepared"], BEV],
  ["Coffee, brewed", ["coffee", "brewed", "prepared with tap water"], BEV],
  ["Espresso", ["coffee", "espresso", "restaurant-prepared"], BEV],
  ["Tea, brewed", ["tea", "brewed", "prepared with tap water"], BEV],
  ["Green tea", ["tea", "green", "brewed"], BEV],
  ["Cola", ["beverages, carbonated, cola", "regular"], BEV],
  ["Diet cola", ["carbonated, low calorie", "cola or pepper-type", "aspartame", "contains caffeine"], BEV],
  ["Sports drink", ["gatorade", "ready-to-drink"], BEV],
  ["Energy drink", ["energy drink", "sugar free"], BEV],
  ["Beer, regular", ["alcoholic beverage", "beer", "regular", "all"], BEV],
  ["Beer, light", ["alcoholic beverage", "beer", "light"], BEV],
  ["Wine, red", ["alcoholic beverage", "wine", "table", "red"], BEV],
  ["Wine, white", ["alcoholic beverage", "wine", "table", "white"], BEV],
  ["Liquor, 80 proof", ["alcoholic beverage", "distilled", "80 proof"], BEV],
  ["Water", ["water", "bottled", "generic"], BEV],

  /* ------------------------------------------------- condiments & sauces */
  ["Ketchup", ["catsup"], SAU],
  ["Mustard, yellow", ["mustard", "prepared", "yellow"], SP],
  ["Soy sauce", ["soy sauce", "soy and wheat"], SAU],
  ["Sriracha", ["sauce", "hot chile", "sriracha"], SAU],
  ["BBQ sauce", ["sauce", "barbecue"], SAU],
  ["Marinara sauce", ["sauce", "pasta", "spaghetti"], SAU],
  ["Alfredo sauce", ["sauce", "cheese", "ready-to-serve"], SAU],
  ["Teriyaki sauce", ["sauce", "teriyaki", "ready-to-serve"], SAU],
  ["Worcestershire sauce", ["sauce", "worcestershire"], SAU],
  ["Fish sauce", ["sauce", "fish", "ready-to-serve"], SAU],
  ["Pesto", ["sauce", "pesto"], SAU],
  ["Vinegar, balsamic", ["vinegar", "balsamic"], SP],
  ["Vinegar, apple cider", ["vinegar", "cider"], SP],
  ["Salt", ["salt", "table"], SP],
  ["Black pepper", ["spices", "pepper", "black"], SP],
  ["Cinnamon", ["spices", "cinnamon", "ground"], SP],
  ["Garlic powder", ["spices", "garlic powder"], SP],
  ["Onion powder", ["spices", "onion powder"], SP],
  ["Paprika", ["spices", "paprika"], SP],
  ["Cumin", ["spices", "cumin seed"], SP],
  ["Chili powder", ["spices", "chili powder"], SP],
  ["Oregano, dried", ["spices", "oregano", "dried"], SP],
  ["Basil, fresh", ["basil", "fresh"], SP],
  ["Ginger, raw", ["ginger root", "raw"], V],
  ["Cilantro, fresh", ["coriander", "cilantro", "raw"], SP],
  ["Parsley, fresh", ["parsley", "fresh"], V],
  ["Baking powder", ["leavening agents", "baking powder", "!low-sodium"], BK],
  ["Baking soda", ["leavening agents", "baking soda"], BK],
  ["Cocoa powder, unsweetened", ["cocoa", "dry powder", "unsweetened"], SW],
  ["Vanilla extract", ["vanilla extract"], SP],
  ["Gelatin, dry", ["gelatins", "dry powder", "unsweetened"], SW],
  ["Cornstarch", ["cornstarch"], G],
  ["Broth, chicken", ["soup", "chicken broth", "ready-to-serve"], SAU],
  ["Broth, beef", ["soup", "beef broth", "ready-to-serve"], SAU],
  ["Chicken stock", ["soup", "stock", "chicken", "home-prepared"], SAU],

  /* -------------------------------------------------- sugars & sweeteners */
  ["Sugar, white", ["sugars", "granulated"], SW],
  ["Brown sugar", ["sugars", "brown"], SW],
  ["Powdered sugar", ["sugars", "powdered"], SW],
  ["Honey", ["honey"], SW],
  ["Maple syrup", ["syrups", "maple"], SW],
  ["Agave syrup", ["sweetener", "syrup, agave"], SW],
  ["Molasses", ["molasses"], SW],
  ["Pancake syrup", ["syrups", "table blends", "pancake"], SW],
  ["Stevia", ["sweetener", "herbal extract powder", "stevia"], SW],
  ["Splenda / sucralose", ["sweetener", "sucralose"], SW],
  ["Jam / preserves", ["jams and preserves"], SW],
  ["Jelly", ["jellies"], SW],
  ["Nutella / chocolate hazelnut spread", ["chocolate-flavored hazelnut spread"], SW],
  ["Chocolate chips, semisweet", ["candies", "semisweet chocolate"], SW],
  ["Dark chocolate, 70%", ["chocolate, dark", "70-85%"], SW],
  ["Milk chocolate", ["candies", "milk chocolate"], SW],
  ["White chocolate", ["candies", "white chocolate"], SW],
  ["Marshmallows", ["candies", "marshmallows"], SW],
  ["Gummy candy", ["candies", "gumdrops"], SW],
  ["Hard candy", ["candies", "hard"], SW],

  /* ------------------------------------------- snacks, baked, prepared */
  ["Potato chips", ["snacks", "potato chips", "plain", "salted"], SN],
  ["Tortilla chips", ["snacks", "tortilla chips", "plain"], SN],
  ["Popcorn, air-popped", ["snacks", "popcorn", "air-popped"], SN],
  ["Popcorn, microwave", ["snacks", "popcorn", "microwave", "!low fat"], SN],
  ["Pretzels", ["snacks", "pretzels", "hard", "plain", "salted"], SN],
  ["Trail mix", ["snacks", "trail mix", "regular"], SN],
  ["Granola bar", ["snacks", "granola bars", "hard", "plain"], SN],
  ["Cookies, chocolate chip", ["cookies", "chocolate chip", "commercially prepared"], BK],
  ["Cookies, oatmeal", ["cookies", "oatmeal", "commercially prepared"], BK],
  ["Brownie", ["brownies", "commercially prepared"], BK],
  ["Cake with chocolate frosting", ["cake", "chocolate frosting", "commercially prepared"], BK],
  ["Cheesecake", ["cheesecake", "commercially prepared"], BK],
  ["Donut, glazed", ["doughnuts", "yeast-leavened", "glazed"], BK],
  ["Muffin, blueberry", ["muffins", "blueberry", "commercially prepared"], BK],
  ["Pie, apple", ["pie", "apple", "commercially prepared"], BK],
  ["Pizza, cheese", ["pizza", "cheese topping", "regular crust"], BK],
  ["Pizza, pepperoni", ["pizza", "pepperoni topping", "regular crust"], BK],
  ["Mac and cheese, prepared", ["macaroni and cheese", "box mix", "prepared"], G],
  ["Chicken noodle soup", ["soup", "chicken noodle", "canned", "prepared"], SAU],
  ["Tomato soup", ["soup, tomato", "canned", "prepared", "!rice", "!beef"], SAU],
  ["Chili with beans, canned", ["chili with beans", "canned"], SAU],
  ["Protein powder, whey", ["whey protein powder isolate"], D],
];
